language: c

sudo: false

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/8.2.2/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.2.2

script:
  - stack -j 2 build --no-terminal
  - stack --no-terminal --skip-ghc-check test

